version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=joselatino
      - POSTGRES_PASSWORD=3612
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
